restaurant:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('RESTAURANT_DB_PATH') }}"
      threads: 4
    prod:
      type: duckdb
      path: "{{ env_var('RESTAURANT_DB_PATH') }}"
      threads: 8
